// Integration tests entry — DB, API, heavy I/O
process.env.CLAUDESTAT_DB_PATH ??= ':memory:'
process.env.CLAUDESTAT_DATA_DIR ??= require('os').tmpdir()

require('./api-events.test')
require('./api-stream.test')
require('./billing-blocks.test')
require('./daily-activity.test')
require('./db.test')
require('./db-advanced.test')
require('./doctor.test')
require('./enricher.test')
require('./enricher-async.test')
require('./export.test')
require('./install.test')
require('./intelligence.test')
require('./kill-switch.test')
require('./orchestration.test')
require('./project-scanner.test')
require('./quota-api.test')
require('./quota-tracker.test')
require('./semantic.test')
require('./semantic-loops.test')
require('./top.test')
require('./watchdog.test')
