import { AlertTriangle, Shield } from 'lucide-react'
import type { CostInfo } from '../../../types'
import { Tip } from '../../Tip'
import { PRICE_PER_M, cacheSavingsPerM, fmtTok, fmtUsd } from '../utils'
import { Card, CardHeader } from './StatusCard'

// ─── Card: Cache ───────────────────────────────────────────────────────────────

const CACHE_BAR_TIPS: Record<string, string> = {
  'cache hit':    'Tokens served from prompt cache. They are ~10× cheaper than fresh input. Indicates how much context Claude already "remembered" without reprocessing.',
  'cache create': 'Tokens written to cache for the first time. Paid once and reused in subsequent reads. More expensive than fresh input but amortize over time.',
  'input fresh': 'New context that Claude processed without prior cache — full input price.',
  'output':       'Tokens generated by Claude in responses. They are the most expensive (~3× more than input in Sonnet).',
}

export function CacheCard({ cost }: { cost: CostInfo }) {
  const { input_tokens, cache_read, cache_creation, output_tokens } = cost
  const total   = input_tokens + cache_read + cache_creation + output_tokens
  const hitRate = total > 0 ? Math.round((cache_read / (input_tokens + cache_read + cache_creation)) * 100) : 0
  const savings = (cache_read / 1_000_000) * cacheSavingsPerM(cost.model)
  const color   = hitRate >= 70 ? '#3fb950' : hitRate >= 40 ? '#d29922' : '#f85149'

  const bars = [
    { label: 'cache hit',    color: '#3fb95099', tokens: cache_read,    pct: total > 0 ? cache_read / total * 100 : 0 },
    { label: 'cache create', color: '#58a6ff55', tokens: cache_creation, pct: total > 0 ? cache_creation / total * 100 : 0 },
    { label: 'input fresh', color: '#8b949e55', tokens: input_tokens,  pct: total > 0 ? input_tokens / total * 100 : 0 },
    { label: 'output',       color: '#d2992255', tokens: output_tokens, pct: total > 0 ? output_tokens / total * 100 : 0 },
  ].filter(b => b.tokens > 0)

  return (
    <Card>
      <CardHeader icon={Shield} title="Cache efficiency" subtitle="current session" color={color} />
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 10 }}>
        <span style={{ fontSize: 28, fontWeight: 700, color, fontVariantNumeric: 'tabular-nums', lineHeight: 1 }}>
          {hitRate}%
        </span>
        <div>
          <div style={{ fontSize: 11, color: '#e6edf3' }}>cache hit rate</div>
          {savings > 0.001 && (
            <div style={{ fontSize: 10, color: '#3fb950' }}>~{fmtUsd(savings)} saved</div>
          )}
          <Tip position="bottom" align="left" content={
            <div>
              <div style={{ color: '#58a6ff', fontWeight: 700, fontSize: 11, marginBottom: 3 }}>Why 70%?</div>
              <div style={{ color: '#8b949e', fontSize: 10, lineHeight: 1.5 }}>
                Below 70% cache savings are marginal. In long and continuous sessions hit rate naturally rises. Avoid using /clear in the middle of a session to not lose accumulated cache.
              </div>
            </div>
          }><span style={{ fontSize: 9, color: '#484f58', cursor: 'help', textDecoration: 'underline dotted' }}>target ≥70%</span></Tip>
        </div>
      </div>
      <div style={{ height: 8, background: '#21262d', borderRadius: 4, overflow: 'hidden', display: 'flex', marginBottom: 10 }}>
        {bars.map(b => (
          <div key={b.label} style={{ width: `${b.pct}%`, height: '100%', background: b.color }} />
        ))}
      </div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 14px' }}>
        {bars.map(b => (
          <Tip key={b.label} position="top" align="left" content={
            <div>
              <div style={{ color: b.color.substring(0, 7), fontWeight: 700, fontSize: 11, marginBottom: 3 }}>{b.label}</div>
              <div style={{ color: '#8b949e', fontSize: 10, lineHeight: 1.5 }}>{CACHE_BAR_TIPS[b.label] ?? ''}</div>
            </div>
          }>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4, cursor: 'help' }}>
              <div style={{ width: 8, height: 8, borderRadius: 2, background: b.color, flexShrink: 0 }} />
              <span style={{ fontSize: 10, color: '#6e7681' }}>{fmtTok(b.tokens)}</span>
              <span style={{ fontSize: 10, color: '#484f58' }}>{b.label}</span>
            </div>
          </Tip>
        ))}
      </div>
    </Card>
  )
}

// ─── Card: Loops ───────────────────────────────────────────────────────────────

export function LoopsCard({ cost }: { cost: CostInfo }) {
  const { loops, efficiency_score } = cost
  const totalLoops  = loops?.reduce((s, l) => s + l.count, 0) ?? 0
  const wastedUsd   = (totalLoops * 1_200 / 1_000_000) * PRICE_PER_M.sonnet
  const scoreColor  = efficiency_score >= 90 ? '#3fb950' : efficiency_score >= 70 ? '#d29922' : '#f85149'

  return (
    <Card>
      <CardHeader icon={AlertTriangle} title="Loops and efficiency" subtitle="current session" color={totalLoops > 0 ? '#f85149' : '#3fb950'} />
      <div style={{ display: 'flex', gap: 16, marginBottom: totalLoops > 0 ? 10 : 0 }}>
        <div>
          <div style={{ fontSize: 26, fontWeight: 700, color: totalLoops > 0 ? '#f85149' : '#3fb950', lineHeight: 1 }}>
            {totalLoops}
          </div>
          <div style={{ fontSize: 9, color: '#484f58' }}>loops detected</div>
        </div>
        <Tip position="bottom" align="left" content={
          <div>
            <div style={{ color: scoreColor, fontWeight: 700, fontSize: 11, marginBottom: 3 }}>Efficiency score</div>
            <div style={{ color: '#8b949e', fontSize: 10, lineHeight: 1.5 }}>
              100 = no loops detected.<br />
              ~5 points deducted for each repeated tool in a block.<br />
              Below 70 indicates inefficient session with wasted tokens.
            </div>
          </div>
        }>
          <div style={{ cursor: 'help' }}>
            <div style={{ fontSize: 26, fontWeight: 700, color: scoreColor, lineHeight: 1 }}>
              {efficiency_score}
            </div>
            <div style={{ fontSize: 9, color: '#484f58' }}>efficiency /100</div>
          </div>
        </Tip>
        {totalLoops > 0 && (
          <Tip position="bottom" align="left" content={
            <div>
              <div style={{ color: '#d29922', fontWeight: 700, fontSize: 11, marginBottom: 3 }}>Lost cost estimate</div>
              <div style={{ color: '#8b949e', fontSize: 10, lineHeight: 1.5 }}>
                Calculated as: loops × ~1,200 tokens × blended Sonnet price.<br />
                This is a conservative estimate — actual cost may be higher if loops involve large files.
              </div>
            </div>
          }>
            <div style={{ cursor: 'help' }}>
              <div style={{ fontSize: 16, fontWeight: 600, color: '#d29922', lineHeight: 1 }}>
                ~{fmtUsd(wastedUsd)}
              </div>
              <div style={{ fontSize: 9, color: '#484f58' }}>wasted tokens</div>
            </div>
          </Tip>
        )}
      </div>
      {totalLoops > 0 && loops && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginBottom: 8 }}>
          {loops.map((l, i) => (
            <span key={i} style={{ fontSize: 11, color: '#f85149', background: '#f8514914', border: '1px solid #f8514930', borderRadius: 4, padding: '2px 7px' }}>
              {l.toolName} ×{l.count}
            </span>
          ))}
        </div>
      )}
      <div style={{ height: 3, background: '#21262d', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{ width: `${efficiency_score}%`, height: '100%', background: scoreColor, borderRadius: 2, transition: 'width 0.5s' }} />
      </div>
    </Card>
  )
}
